/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.pm2.fats.gui;

import javafx.application.Application;
import javafx.application.HostServices;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;
import java.io.File;

/**
 * The main class for the start of the gui Application
 */
public class AppGUI extends Application {
    private final HostServices services = this.getHostServices();

    /**
     * Start the Application and launch it.
     *
     * @param primaryStage The primaryStage object from javafx.
     */
    @Override
    public void start(Stage primaryStage) {
        mainWindow(primaryStage);
    }

    /**
     * Loads the main window.
     *
     * @param primaryStage The primaryStage object from javafx.
     */
    private void mainWindow(Stage primaryStage) {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource("StartWindow.fxml"));
            Pane startPane = loader.load();

            Scene playScene = new Scene(startPane);
            primaryStage.setScene(playScene);
            primaryStage.sizeToScene();
            primaryStage.setTitle("Strategy Tank");
            File file = new File("ch/zhaw/pm2/fats/items", "tank.png");
            primaryStage.getIcons().add(new Image(file.toString()));

            StartWindowController playWindowController = loader.getController();
            playWindowController.setService(services);

            primaryStage.show();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}